### ISSUE TITLE
Need unique icon/logo

### ISSUE THREAD

**Issue by JakeC1020** [JakeC1020/quote-verifier-chrome-extension#2]
I was thinking maybe something with quotation marks, however Google Hangouts does that to an extent. I was also considering blue, as blue == security, reliability in general.

**Comment by ryanrouleau** [comment]
I like the quotation mark idea.  I think having it blue is enough to make it distinguishable from hangouts.  
We should consider following Google's material design guidelines: https://www.google.com/design/spec/style/icons.html

**Comment by JakeC1020** [comment]
How are your graphic design skills?
