### ISSUE TITLE
Get rid of traces of initializer 

### ISSUE THREAD

**Issue by JakeC1020** [JakeC1020/quote-verifier-chrome-extension#3]
The chrome extension generator left us with all sorts of stuff we don't need, and I also didn't thoroughly  change all of its messages and manifest stuff. Someone needs to go through and make sure we have our info in all those places.

**Comment by ryanrouleau** [comment]
I can go through and clean stuff up.  Does it use any jquery or is it purely angular?

**Comment by JakeC1020** [comment]
It's all Angular, I never ended up needing jQuery.
